services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cheunrywang/turtle-website:latest
    ports:
      - "8080:80"
    container_name: turtle-website-front
    restart: unless-stopped
